/**
 * Sidebar configuration for Docusaurus
 * Auto-generates sidebar from docs/ folder structure (FR-006, T042)
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generated sidebar based on docs/ directory structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
