/**
 * Sidebar configuration for Docusaurus
 * Auto-generates sidebar from docs/ folder structure (FR-006, T042)
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Manual sidebar to ensure intro appears first (FR-006, T042)
  tutorialSidebar: [
    'intro', // Welcome page appears first
    {
      type: 'autogenerated',
      dirName: '.', // Auto-generate the rest (chapters)
    },
  ],
};

module.exports = sidebars;
