/**
 * Sidebar configuration for Docusaurus
 * Auto-generates sidebar from docs/ folder structure (FR-006, T042)
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Manual sidebar configuration: Welcome first, then auto-generated chapters (FR-006, T042)
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Physical AI',
      items: [{ type: 'autogenerated', dirName: 'chapter-01' }],
    },
    {
      type: 'category',
      label: 'Chapter 2: Basics of Humanoid Robotics',
      items: [{ type: 'autogenerated', dirName: 'chapter-02' }],
    },
    {
      type: 'category',
      label: 'Chapter 3: ROS 2 Fundamentals',
      items: [{ type: 'autogenerated', dirName: 'chapter-03' }],
    },
    {
      type: 'category',
      label: 'Chapter 4: Digital Twin Simulation',
      items: [{ type: 'autogenerated', dirName: 'chapter-04' }],
    },
    {
      type: 'category',
      label: 'Chapter 5: Vision-Language-Action Systems',
      items: [{ type: 'autogenerated', dirName: 'chapter-05' }],
    },
    {
      type: 'category',
      label: 'Chapter 6: Capstone Project',
      items: [{ type: 'autogenerated', dirName: 'chapter-06' }],
    },
  ],
};

module.exports = sidebars;
